---
title: "Which World?"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("pander", repos = "https://cran.rstudio.com")
# install.packages("xlsx", repos = "https://cran.rstudio.com")
library(xlsx)
library(pander)
library(knitr)
panderOptions('table.split.table', Inf)
panderOptions('table.alignment.rownames', 'left')
panderOptions('table.alignment.default', 'right')
options(width=180)
```

```{r, data, echo = FALSE, results = 'hide'}
quiz0418 <- read.xlsx("../data/quiz0418.xlsx", 1, startRow = 2, endRow = 66, colIndex = c(3:7, 9:14), colClasses = c(rep("character", 11)), stringsAsFactors=FALSE)
str(quiz0418)
names(quiz0418) <- c("dept", "id", "name", "year", "e.mail", "cell.no", "Q1", "Q2", "Q3", "Q4", "group")
quiz0418$dept <- factor(quiz0418$dept)
quiz0418$year <- factor(quiz0418$year)
quiz0418$group <- factor(quiz0418$group, levels = c("Red", "Black"))
quiz0418$Q1 <- factor(quiz0418$Q1, levels = c("가", "나", "다", "라", "마"), labels = c("10%", "25%", "33%", "45%", "50%"))
quiz0418$Q2 <- factor(quiz0418$Q2, levels = c("가", "나", "다", "라", "마"), labels = c("10%", "25%", "33%", "45%", "50%"))
quiz0418$Q3 <- factor(quiz0418$Q3, levels = c("가", "나", "다", "라", "마"), labels = c("미국", "터키", "칠레", "대한민국", "멕시코"))
quiz0418$Q4.2 <- quiz0418$Q4
Red <- quiz0418$group == "Red"
Black <- quiz0418$group == "Black"
quiz0418$Q4.2[Red & quiz0418$Q4.2 == "가"] <- "내가 남보다"
quiz0418$Q4.2[Red & quiz0418$Q4.2 == "나"] <- "남이 나보다"
quiz0418$Q4.2[Black & quiz0418$Q4.2 == "가"] <- "남이 나보다"
quiz0418$Q4.2[Black & quiz0418$Q4.2 == "나"] <- "내가 남보다"
quiz0418$Q4.2[quiz0418$Q4.2 == "NA"] <- NA
quiz0418$Q4.2 <- factor(quiz0418$Q4.2, level = c("내가 남보다", "남이 나보다"))
quiz0418$Q4
```

```{r, randomization, echo = FALSE, results = 'hide'}
pander(summary(quiz0418))
```

<!--### 퀴즈 응답 비교{#퀴즈}

#### 소득 상위 10%의 소득점유율

##### 나의 판단

```{r, income concentration, echo = FALSE}
pander(addmargins(table(quiz0418$group, quiz0418$Q1, exclude = NULL), margin=1))
```

##### 나의 판단 (%)

```{r, income concentration in percentage, echo = FALSE}
pander(round(prop.table(addmargins(table(quiz0418$group, quiz0418$Q1, exclude = NULL), margin=1), margin=1)[4,]*100, digits=1))
```

#### 소득 상위 10%의 소득점유율

##### 적정 수준

```{r, your judgement, echo = FALSE}
pander(addmargins(table(quiz0418$group, quiz0418$Q2, exclude = NULL), margin=1))
```

##### 적정 수준 (%)

```{r, your judgement in percentage, echo = FALSE}
pander(round(prop.table(addmargins(table(quiz0418$group, quiz0418$Q2, exclude = NULL), margin=1), margin=1)[4,]*100, digits=1), caption="적정 수준")
```

#### OECD 국가 지니계수 개선도

##### 가장 낮은 나라

```{r, gini coefficient improvement, echo = FALSE}
pander(addmargins(table(quiz0418$group, quiz0418$Q3, exclude = NULL), margin=1))
```

##### 가장 낮은 나라 (%)

```{r, gini coefficient improvement in percentage, echo = FALSE}
pander(round(prop.table(addmargins(table(quiz0418$group, quiz0418$Q3, exclude = NULL), margin = 1), margin = 1)[4,]*100, digits = 1), caption = "지니계수 개선도")
```

-->
### 내가 살고 싶은 세상

#### 내가 남보다, 혹은 남이 나보다

##### 소득의 절대값이 아니라 상대 비교가 중요하다는 Solnick and Hemenway(1998)의 연구결과와 일치. 랜덤화하였지만 응답에는 차이가 없음.

```{r, social comparison, echo = FALSE}
tbl <- table(quiz0418$group, quiz0418$Q4.2, exclude = NULL)[1:2, ]
tbl.a <- addmargins(tbl)
pander(tbl.a, caption="장기기증의사")
```

##### % 비교.  

```{r, social comparison in percentage, echo = FALSE}
merge.tbl <- table(quiz0418$group, quiz0418$Q4.2)
pander(round(prop.table(merge.tbl, margin = 1)*100, digits = 1))
```

##### 합산

```{r, column sums, echo = FALSE}
merge.tbl.m <- margin.table(merge.tbl, margin = 2)
merge.tbl.m.p <- merge.tbl.m / sum(merge.tbl.m)
pander(round(merge.tbl.m.p*100, digits = 1))
```


```{r, save, echo = FALSE}
#save.image("../R/quiz0418.rda")
```