---
title: "Monty Hall"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("pander", repos = "https://cran.rstudio.com")
# install.packages("xlsx", repos = "https://cran.rstudio.com")
library(xlsx)
library(pander)
library(knitr)
panderOptions('table.split.table', Inf)
panderOptions('table.alignment.rownames', 'left')
panderOptions('table.alignment.default', 'right')
options(width = 180)
```

```{r, data, echo = FALSE, results = 'hide'}
quiz0504 <- read.xlsx("../data/quiz0504.xlsx", 1, startRow = 2, endRow = 66, colIndex = c(3:7, 9:14), colClasses = c(rep("character", 11)), stringsAsFactors = FALSE)
str(quiz0504)
names(quiz0504) <- c("dept", "id", "name", "year", "e.mail", "cell.no", "Q1", "Q2", "Q3", "Q4", "group")
quiz0504$dept <- factor(quiz0504$dept)
quiz0504$year <- factor(quiz0504$year)
quiz0504$group <- factor(quiz0504$group, levels = c("Red", "Black"))
quiz0504$Q1 <- factor(quiz0504$Q1, levels = c("가", "나", "다", "라"), labels = c("지천태", "천지비", "풍뢰익", "산택손"))
quiz0504$Q2 <- factor(quiz0504$Q2, levels = c("가", "나", "다", "라"), labels = c("높을떄 높다", "낮을떄 낮다", "높을떄 낮다", "높아지면 낮아진다"))
quiz0504$Q3 <- factor(quiz0504$Q3, levels = c("가", "나", "다", "라"), labels = c("있다", "없다", "있는듯하다", "게층별로 차이"))
quiz0504$Q4.2 <- quiz0504$Q4
quiz0504$Q4.2[quiz0504$group == "Black" & quiz0504$Q4.2 == "가"] <- "바꾼다"
quiz0504$Q4.2[quiz0504$group == "Black" & quiz0504$Q4.2 == "나"] <- "고수한다"
quiz0504$Q4.2[quiz0504$group == "Red" & quiz0504$Q4.2 == "가"] <- "고수한다"
quiz0504$Q4.2[quiz0504$group == "Red" & quiz0504$Q4.2 == "나"] <- "바꾼다"
str(quiz0504)
```

```{r, randomization, echo = FALSE, results = 'hide'}
pander(summary(quiz0504))
```

<!--
### 퀴즈 응답 비교

#### 1993 ~ 2012 미국 소득증가 집단별 비교

##### 풍뢰익

```{r, book of change, echo = FALSE}
pander(addmargins(table(quiz0504$group, quiz0504$Q1, exclude = NULL), margin=1))
```

##### 풍뢰익(%)

```{r, book of change in percentage, echo = FALSE}
pander(round(prop.table(addmargins(table(quiz0504$group, quiz0504$Q1, exclude = NULL), margin=1), margin=1)[4,]*100, digits=1))
```

#### Marginal Tax Rates vs Top 1% Income Shares

##### Quite the opposite

```{r, opposite, echo = FALSE}
pander(addmargins(table(quiz0504$group, quiz0504$Q2, exclude = NULL), margin=1))
```

##### Quite the opposite (%)

```{r, opposite in percentage, echo = FALSE}
pander(round(prop.table(addmargins(table(quiz0504$group, quiz0504$Q2, exclude = NULL), margin=1), margin=1)[4,]*100, digits=1), caption="한계세율과 상위 1%  소득점유")
```

#### 소득10분위 가계 동향

##### 낙수효과?

```{r, MTR, echo = FALSE}
pander(addmargins(table(quiz0504$group, quiz0504$Q3, exclude = NULL), margin=1))
```

##### 낙수효과? (%)

```{r, MTRE in percentage, echo = FALSE}
pander(round(prop.table(addmargins(table(quiz0504$group, quiz0504$Q3, exclude = NULL), margin = 1), margin = 1)[4,]*100, digits = 1), caption = "낙수효과?")
```

### Monty Hall 문제
-->

#### Switch or not?

##### 염소가 들어있는 문을 보여줌으로써 다른 문에 자동차가 들어 있을 확률은 1/3에서 2/3로 늘어나므로 바꾸는 것이 적절한 판단임. Red와 Black의 차이는 "바꾼다"와 "고수한다"의 순서를 바꾼 것인데 통계적으로 유의한 차이는 발견되지 아니한다.

<!--아니지만 Black 집단에서 나.에 배치한 선택을 "고수한다"에 많은 인원이 몰린점이 흥미롭다.-->  

```{r, Monty Hall, echo = FALSE}
tbl <- table(quiz0504$group, quiz0504$Q4.2, exclude = NULL)[1:2, ]
tbl.a <- addmargins(tbl)
kable(tbl.a, caption="Monty Hall")
```

##### % 비교.  

```{r, Monty Hall in percentage, echo = FALSE}
merge.tbl <- table(quiz0504$group, quiz0504$Q4.2)
kable(round(prop.table(merge.tbl, margin = 1)*100, digits = 1))
````

##### 합산

```{r, column sums, echo = FALSE}
merge.tbl.m <- margin.table(merge.tbl, margin = 2)
merge.tbl.m.p <- merge.tbl.m / sum(merge.tbl.m)
pander(round(merge.tbl.m.p*100, digits = 1))
```

```{r, save, echo = FALSE}
#save.image("../R/quiz0504.rda")
```