---
title: "Quiz 160321"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("pander", repos = "https://cran.rstudio.com")
# install.packages("xlsx", repos = "https://cran.rstudio.com")
library(xlsx)
library(pander)
library(knitr)
panderOptions('table.split.table', Inf)
panderOptions('table.alignment.rownames', 'left')
panderOptions('table.alignment.default', 'right')
options(width=180)
```

```{r, data, echo = FALSE, results = 'hide'}
quiz0321 <- read.xlsx("../data/quiz0321.xlsx", 1, startRow = 2, endRow = 66, colIndex = c(3:7, 9:14), colClasses=c(rep("character", 11)), stringsAsFactors=FALSE)
str(quiz0321)
names(quiz0321) <- c("dept", "id", "name", "year", "e.mail", "cell.no", "Q1", "Q2", "Q3", "Q4", "group")
quiz0321$dept <- factor(quiz0321$dept)
quiz0321$year <- factor(quiz0321$year)
quiz0321$group <- factor(quiz0321$group, levels = c("Red", "Black"))
quiz0321$Q1 <- factor(quiz0321$Q1, levels = c("가", "나", "다", "라", "마"), labels = c("90%", "80%", "50%", "20%", "10%"))
quiz0321$Q2 <- factor(quiz0321$Q2, levels = c("가", "나", "다", "라"), labels = c("대한민국", "영국", "이탈리아", "미국"))
quiz0321$Q3 <- factor(quiz0321$Q3, levels = c("가", "나", "다", "라", "마"), labels = c("중위임금60%낮음", "실직가능성2배", "좋지않은건강", "활동참여미흡", "타인신뢰부족"))
quiz0321$Q4 <- factor(quiz0321$Q4, levels = c("1", "2", "3", "4", "5", "0"))
quiz0321$Q4.2 <- quiz0321$Q4
levels(quiz0321$Q4.2[quiz0321$group == "Black"]) <- c("4", "3", "2", "1", "5", "0")
levels(quiz0321$Q4.2) <- c("A", "B", "C", "D", "E", "기타 또는 없음")
str(quiz0321)
```

```{r, randomization, echo = FALSE, results = 'hide'}
pander(summary(quiz0321))
```

### 퀴즈 응답 비교

#### 해방직후 비문해율

##### 비문해율

```{r, illiteracy rate, echo = FALSE}
pander(addmargins(table(quiz0321$group, quiz0321$Q1, exclude = NULL), margin=1))
```

##### 비문해율(%)

```{r, illiteracy rate in percentage, echo = FALSE}
pander(round(prop.table(addmargins(table(quiz0321$group, quiz0321$Q1, exclude = NULL), margin=1), margin=1)[4,]*100, digits=1))
```

#### OECD 20대와 50대 문해력 격차

##### 문해력 격차

```{r, literacy rates difference, echo = FALSE}
pander(addmargins(table(quiz0321$group, quiz0321$Q2, exclude = NULL), margin=1))
```

##### 문해력 격차(%)

```{r, literacy rates difference in percentage, echo = FALSE}
pander(round(prop.table(addmargins(table(quiz0321$group, quiz0321$Q2, exclude = NULL), margin=1), margin=1)[4,]*100, digits=1), caption="공법도입과 대신들")
```

#### 문해력이 낮은 집단은 높은 집단 보다  

##### 문해력이 낮으면?(집계표)

```{r, tax law and laymen, echo = FALSE}
pander(addmargins(table(quiz0321$group, quiz0321$Q3, exclude = NULL), margin=1))
```

##### 문해력이 낮으면?(%)

```{r, tax law and laymen in percentage, echo = FALSE}
pander(round(prop.table(addmargins(table(quiz0321$group, quiz0321$Q3, exclude = NULL), margin=1), margin=1)[4,]*100, digits=1), caption="품관촌민들의 찬반")
```

### 정당 지지도

#### 질문지 답 문항 순서의 영향

##### 의석수 순으로 정당 이름을 늘어놓는지(Red), 의석수 역순으로 정당 이름을 늘어놓는지(Black)에 따라 응답이 달라질 것으로 기대. Red 와 Black의 응답이 다르게 나타나고 있는 점에 유의. 

```{r, outs merge, echo = FALSE}
pander(table(quiz0321$group, quiz0321$Q4.2, exclude = NULL), caption="야권통합논란")
```

##### % 비교.  

```{r, outs merge in percentage, echo = FALSE}
merge.tbl <- table(quiz0321$group, quiz0321$Q4.2)
pander(round(prop.table(merge.tbl, margin = 1)*100, digits = 1))
```

```{r, save, echo = FALSE}
#save.image("../R/quiz0321.rda")
```