---
title: "Quiz 160328"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("pander", repos = "https://cran.rstudio.com")
# install.packages("xlsx", repos = "https://cran.rstudio.com")
library(xlsx)
library(pander)
library(knitr)
panderOptions('table.split.table', Inf)
panderOptions('table.alignment.rownames', 'left')
panderOptions('table.alignment.default', 'right')
options(width=180)
```

```{r, data, echo = FALSE, results = 'hide'}
quiz0328 <- read.xlsx("../data/quiz0328.xlsx", 1, startRow = 2, endRow = 66, colIndex = c(3:7, 9:14), colClasses=c(rep("character", 11)), stringsAsFactors=FALSE)
str(quiz0328)
names(quiz0328) <- c("dept", "id", "name", "year", "e.mail", "cell.no", "Q1", "Q2", "Q3", "Q4", "group")
quiz0328$dept <- factor(quiz0328$dept)
quiz0328$year <- factor(quiz0328$year)
quiz0328$group <- factor(quiz0328$group, levels = c("Red", "Black"))
quiz0328$Q1 <- factor(quiz0328$Q1, levels = c("가", "나", "다", "라"), labels = c("독서율", "독서량", "도서구입률", "도서구입량"))
quiz0328$Q2 <- factor(quiz0328$Q2, levels = c("가", "나", "다", "라", "마"), labels = c("90%", "80%", "70%", "60%", "50%"))
quiz0328$Q3 <- factor(quiz0328$Q3, levels = c("가", "나", "다", "라", "마"), labels = c("90%", "80%", "70%", "60%", "50%"))
quiz0328$Q4 <- factor(quiz0328$Q4, levels = c("가", "나"))
quiz0328$Q4.2 <- quiz0328$Q4
levels(quiz0328$Q4.2[quiz0328$group == "Black"]) <- c("나", "가")
levels(quiz0328$Q4.2) <- c("투표할 것이다", "투표하지 않을 것이다")
str(quiz0328)
```

```{r, randomization, echo = FALSE, results = 'hide'}
pander(summary(quiz0328))
```

### 퀴즈 응답 비교

#### 독서율의 정의

##### 독서율

```{r, reader rate, echo = FALSE}
pander(addmargins(table(quiz0328$group, quiz0328$Q1, exclude = NULL), margin=1))
```

##### 독서율(%)

```{r, reader rate in percentage, echo = FALSE}
pander(round(prop.table(addmargins(table(quiz0328$group, quiz0328$Q1, exclude = NULL), margin=1), margin=1)[4,]*100, digits=1))
```

#### 20대와 50대 독서율 격차

##### 20대의 독서율

```{r, reader rates 20 years olds, echo = FALSE}
pander(addmargins(table(quiz0328$group, quiz0328$Q2, exclude = NULL), margin=1))
```

##### 20대의 독서율(%)

```{r, reader rates 20 years olds in percentage, echo = FALSE}
pander(round(prop.table(addmargins(table(quiz0328$group, quiz0328$Q2, exclude = NULL), margin=1), margin=1)[4,]*100, digits=1), caption="20대의 독서율")
```

##### 50대의 독서율

```{r, reader rates 50 years olds, echo = FALSE}
pander(addmargins(table(quiz0328$group, quiz0328$Q3, exclude = NULL), margin=1))
```

##### 50대의 독서율(%)

```{r, reader rates 50 years olds in percentage, echo = FALSE}
pander(round(prop.table(addmargins(table(quiz0328$group, quiz0328$Q3, exclude = NULL), margin=1), margin=1)[4,]*100, digits=1), caption="50대의 독서율")
```

### 투표 참여 의사 파악

#### 질문지 답 문항 순서의 영향

##### 긍정 답안(투표할 것이다)이 먼저 나오는지(Red), 부정 답안(투표하지 않을 것이다)이 먼저 나오는지(Black)에 따라 응답이 달라질 것으로 기대하였으나 응답은 거의 동일하게 나옴.

```{r, vote attitude, echo = FALSE}
pander(table(quiz0328$group, quiz0328$Q4.2, exclude = NULL), caption="투표 참여 의사")
```

##### % 비교.  

```{r, vote attitude in percentage, echo = FALSE}
merge.tbl <- table(quiz0328$group, quiz0328$Q4.2)
pander(round(prop.table(merge.tbl, margin = 1)*100, digits = 1))
```

```{r, save, echo = FALSE}
#save.image("../R/quiz0328.rda")
```